### ISSUE TITLE
form_build_id_elem remains empty?

### ISSUE THREAD

**Issue by Kurdym** [srgrn/grab_packt.py#3]
I used your script scheduled on my NAS. It worked well until August 4.
Today I checked and find this error, when I run from the command prompt.

```
Traceback (most recent call last):
  File "./add_to_lib.py", line 120, in <module>
    main()
  File "./add_to_lib.py", line 68, in main
    book_url = BASE_URL + book_link_elem[0].get('href')
IndexError: list index out of range

```

I tried to debug, but too much I don't know yet.
Login via website goes OK and I'm still able to claim the latest book.

Would you happen to have the same problem and know how to solve this?

**Comment by srgrn** [comment]
Haven't checked it in a while probably a site redesign
Thanks

**Comment by srgrn** [comment]
fixed. thanks for using this. however please note that this is a toy script and isn't that good.
the problem was that the changed their servers to block such requests to prevent running such scripts. I actually registered to the email and haven't bothered with it in a long time.

**Comment by Kurdym** [comment]
Thanks for fixing it. So it was just the no agent that was the problem?
I love your script above others for it's simplicity, the fact that's just 1 script.

**Comment by Kurdym** [comment]
I cheered to early. 
I changed the email passwords to being my strings again, instead of env variables, but that should make no difference.. 

But the output of the pdf now is: 403 forbidden in html.

Does the same happen at your side?
